"""adding priority field to orders table

Revision ID: 2a1b5a6b95b7
Revises: 9402a4ffedac
Create Date: 2026-05-12 13:46:44.142302

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a1b5a6b95b7"
down_revision: Union[str, Sequence[str], None] = "9402a4ffedac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("priority", sa.Integer(), nullable=True))
    op.execute("UPDATE orders SET priority = 4 WHERE priority IS NULL")
    op.alter_column("orders", "priority", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "priority")
    # ### end Alembic commands ###
