"""add webhook field to tenant model

Revision ID: b96bab6d4e08
Revises: 2e3a5e335c88
Create Date: 2026-05-19 20:01:19.950743

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b96bab6d4e08"
down_revision: Union[str, Sequence[str], None] = "2e3a5e335c88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenants", sa.Column("webhook_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "webhook_url")
    # ### end Alembic commands ###
