"""add processing to order status enum

Revision ID: badc59c5f1fe
Revises: a45155f12925
Create Date: 2026-05-19 18:25:21.925543

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'badc59c5f1fe'
down_revision: Union[str, Sequence[str], None] = 'a45155f12925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE orderstatus ADD VALUE 'processing'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ## Can't remove enum values
    # ### end Alembic commands ###
