"""added a new table for failed webhooks

Revision ID: ea0ae988129b
Revises: b96bab6d4e08
Create Date: 2026-05-19 20:12:15.076709

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea0ae988129b"
down_revision: Union[str, Sequence[str], None] = "b96bab6d4e08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dead_letter_webhooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("webhook_url", sa.String(), nullable=False),
        sa.Column("payload", sa.String(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=False),
        sa.Column(
            "failed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dead_letter_webhooks")
    # ### end Alembic commands ###
